'use client';

import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Download, Share2, RefreshCw, Loader2, Mail } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Header } from '@/components/layout/Header';
import { useSession } from '@/context/SessionContext';
import { ANIMATION } from '@/lib/constants';
import type { FeedbackItem } from '@/types';

export function ReflectionScreen() {
  const { state, resetSession, setAnalysis } = useSession();
  const [isLoadingFeedback, setIsLoadingFeedback] = useState(false);

  const analysis = state.analysis;
  const stance = state.initialStance;

  // Fetch feedback if not already loaded
  useEffect(() => {
    const fetchFeedback = async () => {
      if (!analysis || analysis.feedback.length > 0) return;

      setIsLoadingFeedback(true);
      try {
        const response = await fetch('/api/feedback', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            scenario: state.scenario,
            stance: state.initialStance,
            analysis: analysis,
          }),
        });

        if (response.ok) {
          const feedback = await response.json();
          setAnalysis({ ...analysis, feedback });
        }
      } catch (error) {
        console.error('Failed to fetch feedback:', error);
      } finally {
        setIsLoadingFeedback(false);
      }
    };

    fetchFeedback();
  }, [analysis, state.scenario, state.initialStance, setAnalysis]);

  const handleShare = async () => {
    // Create shareable state
    const shareData = {
      scenario: state.scenario?.title,
      initialStance: stance?.decision,
      result: analysis?.primaryRecommendation,
    };

    const shareText = `I analyzed a Make-Buy-Partner decision for "${shareData.scenario}".\nMy instinct: ${shareData.initialStance?.toUpperCase()}\nSystematic analysis: ${shareData.result?.toUpperCase()}\n\nTry it yourself!`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Make-Buy-Partner Analysis',
          text: shareText,
          url: window.location.href,
        });
      } catch {
        // User cancelled or error
      }
    } else {
      // Fallback: copy to clipboard
      await navigator.clipboard.writeText(shareText);
      alert('Results copied to clipboard!');
    }
  };

  const handleDownload = () => {
    // Create a simple text summary for download
    const content = `
MAKE-BUY-PARTNER ANALYSIS SUMMARY
================================

Scenario: ${state.scenario?.title}
${state.scenario?.summary}

INITIAL STANCE
--------------
Decision: ${stance?.decision?.toUpperCase()}
Reasoning: ${stance?.reasoning}

FRAMEWORK ANALYSIS
------------------
${analysis?.frameworkResults.map(r =>
  `${r.framework}: ${r.recommendation.toUpperCase()} (${r.confidence}%)\n  ${r.reasoning}`
).join('\n\n')}

WEIGHTED RESULTS
----------------
Make: ${analysis?.weightedResult.make}%
Buy: ${analysis?.weightedResult.buy}%
Partner: ${analysis?.weightedResult.partner}%

Primary Recommendation: ${analysis?.primaryRecommendation?.toUpperCase()}

FEEDBACK
--------
${analysis?.feedback.map(f => `[${f.type.toUpperCase()}] ${f.title}\n${f.description}`).join('\n\n')}

---
Generated by Make·Buy·Partner Analysis Tool
Columbia Business School · Technology Strategy
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mbp-analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleNewAnalysis = () => {
    if (window.confirm('Start a new analysis? Your current results will be cleared.')) {
      resetSession();
    }
  };

  const handleEmailShare = () => {
    const scenarioTitle = state.scenario?.title || 'Make-Buy-Partner Analysis';
    const initialDecision = stance?.decision?.toUpperCase() || 'N/A';
    const finalDecision = analysis?.primaryRecommendation?.toUpperCase() || 'N/A';

    // Build framework results summary (keep it concise for mailto limits)
    const frameworkSummary = analysis?.frameworkResults
      .map(r => `• ${r.framework}: ${r.recommendation.toUpperCase()} (${r.confidence}%)`)
      .join('\n') || '';

    // Build weighted results
    const weightedSummary = analysis ?
      `Make: ${analysis.weightedResult.make}% | Buy: ${analysis.weightedResult.buy}% | Partner: ${analysis.weightedResult.partner}%` : '';

    // Build the email body (keeping under ~2000 chars for compatibility)
    const emailBody = `
MAKE-BUY-PARTNER ANALYSIS
========================

SCENARIO: ${scenarioTitle}

MY INITIAL INSTINCT: ${initialDecision}
Reasoning: "${stance?.reasoning || 'N/A'}"

FRAMEWORK ANALYSIS:
${frameworkSummary}

WEIGHTED RESULTS:
${weightedSummary}

RECOMMENDATION: ${finalDecision}

${analysis?.primaryRecommendation !== stance?.decision
  ? '→ The systematic analysis suggested a different approach than my initial instinct.'
  : '→ My instinct aligned with the systematic analysis!'}

---
Generated with Make·Buy·Partner Analysis Tool
Columbia Business School | Technology Strategy | Prof. Dan Wang
    `.trim();

    const subject = encodeURIComponent(`Make-Buy-Partner Analysis: ${scenarioTitle}`);
    const body = encodeURIComponent(emailBody);

    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const getFeedbackIcon = (type: FeedbackItem['type']) => {
    switch (type) {
      case 'strength': return '✓';
      case 'consideration': return '⟳';
      case 'flaw': return '!';
    }
  };

  const getFeedbackStyles = (type: FeedbackItem['type']) => {
    switch (type) {
      case 'strength':
        return {
          bg: '#ECFDF5',
          border: '#059669',
          titleColor: '#047857',
          textColor: '#065F46',
        };
      case 'consideration':
        return {
          bg: '#FFFBEB',
          border: '#B4975A',
          titleColor: '#92400E',
          textColor: '#78350F',
        };
      case 'flaw':
        return {
          bg: '#FEF2F2',
          border: '#DC2626',
          titleColor: '#B91C1C',
          textColor: '#991B1B',
        };
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />

      <main id="main-content" className="flex-1 py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-2xl mx-auto">
          <motion.div
            initial={ANIMATION.slideUp.initial}
            animate={ANIMATION.slideUp.animate}
            transition={ANIMATION.slideUp.transition}
          >
            <Card className="shadow-lg border-0">
              <CardHeader className="pb-4">
                <CardTitle className="font-serif text-2xl text-foreground">
                  Reflection
                </CardTitle>
                <div className="w-16 h-1 bg-[#B4975A] rounded-full mt-2" />
              </CardHeader>

              <CardContent className="space-y-6">
                {/* Your Journey */}
                <div className="bg-muted rounded-xl p-6">
                  <div className="flex items-center gap-2 mb-4">
                    <span className="text-xl">🎯</span>
                    <span className="font-semibold text-foreground">Your Journey</span>
                  </div>
                  <p className="text-muted-foreground mb-3">
                    You initially chose{' '}
                    <strong className="text-foreground">
                      {stance?.decision?.toUpperCase()}
                    </strong>{' '}
                    because:
                  </p>
                  <div className="bg-white border-l-4 border-gray-300 rounded-r-lg p-4">
                    <p className="text-sm text-muted-foreground italic">
                      &ldquo;{stance?.reasoning}&rdquo;
                    </p>
                  </div>
                </div>

                {/* Feedback sections */}
                {isLoadingFeedback ? (
                  <div className="text-center py-8">
                    <Loader2 className="w-8 h-8 animate-spin text-primary mx-auto mb-2" />
                    <p className="text-muted-foreground text-sm">Generating personalized feedback...</p>
                  </div>
                ) : (
                  <>
                    {/* Strengths */}
                    {analysis?.feedback.filter(f => f.type === 'strength').map((item, i) => {
                      const styles = getFeedbackStyles(item.type);
                      return (
                        <motion.div
                          key={`strength-${i}`}
                          className="rounded-xl p-6"
                          style={{
                            backgroundColor: styles.bg,
                            borderLeft: `4px solid ${styles.border}`,
                          }}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: i * 0.1 }}
                        >
                          <div className="flex items-center gap-2 mb-3">
                            <span className="text-lg" style={{ color: styles.border }}>
                              {getFeedbackIcon(item.type)}
                            </span>
                            <span className="font-semibold" style={{ color: styles.titleColor }}>
                              {item.title}
                            </span>
                          </div>
                          <p className="text-sm" style={{ color: styles.textColor }}>
                            {item.description}
                          </p>
                        </motion.div>
                      );
                    })}

                    {/* Considerations */}
                    {analysis?.feedback.filter(f => f.type === 'consideration').map((item, i) => {
                      const styles = getFeedbackStyles(item.type);
                      return (
                        <motion.div
                          key={`consideration-${i}`}
                          className="rounded-xl p-6"
                          style={{
                            backgroundColor: styles.bg,
                            borderLeft: `4px solid ${styles.border}`,
                          }}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: 0.2 + i * 0.1 }}
                        >
                          <div className="flex items-center gap-2 mb-3">
                            <span className="text-lg" style={{ color: styles.border }}>
                              {getFeedbackIcon(item.type)}
                            </span>
                            <span className="font-semibold" style={{ color: styles.titleColor }}>
                              {item.title}
                            </span>
                          </div>
                          <p className="text-sm" style={{ color: styles.textColor }}>
                            {item.description}
                          </p>
                        </motion.div>
                      );
                    })}

                    {/* Flaws (if any) */}
                    {analysis?.feedback.filter(f => f.type === 'flaw').map((item, i) => {
                      const styles = getFeedbackStyles(item.type);
                      return (
                        <motion.div
                          key={`flaw-${i}`}
                          className="rounded-xl p-6"
                          style={{
                            backgroundColor: styles.bg,
                            borderLeft: `4px solid ${styles.border}`,
                          }}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: 0.4 + i * 0.1 }}
                        >
                          <div className="flex items-center gap-2 mb-3">
                            <span className="text-lg" style={{ color: styles.border }}>
                              {getFeedbackIcon(item.type)}
                            </span>
                            <span className="font-semibold" style={{ color: styles.titleColor }}>
                              {item.title}
                            </span>
                          </div>
                          <p className="text-sm" style={{ color: styles.textColor }}>
                            {item.description}
                          </p>
                        </motion.div>
                      );
                    })}

                    {/* Key Takeaway */}
                    <div className="bg-blue-50 border-l-4 border-primary rounded-r-xl p-6">
                      <div className="flex items-center gap-2 mb-3">
                        <span className="text-lg">💡</span>
                        <span className="font-semibold text-primary">Key Takeaway</span>
                      </div>
                      <p className="text-[#1E3A5F] leading-relaxed">
                        Systematic frameworks help reveal factors that intuition might overlook.
                        {analysis?.primaryRecommendation !== stance?.decision ? (
                          <> Your initial instinct was reasonable, but the frameworks highlighted
                          important considerations that shifted the recommendation.</>
                        ) : (
                          <> In this case, your instinct aligned well with systematic analysis —
                          a sign of developing strategic intuition!</>
                        )}
                      </p>
                    </div>
                  </>
                )}

                {/* Action buttons */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-4">
                  <Button
                    variant="outline"
                    onClick={handleNewAnalysis}
                    className="flex-1"
                  >
                    <RefreshCw className="mr-2 h-4 w-4" />
                    New Analysis
                  </Button>
                  <Button
                    variant="outline"
                    onClick={handleShare}
                    className="flex-1"
                  >
                    <Share2 className="mr-2 h-4 w-4" />
                    Share
                  </Button>
                  <Button
                    variant="outline"
                    onClick={handleEmailShare}
                    className="flex-1"
                  >
                    <Mail className="mr-2 h-4 w-4" />
                    Email
                  </Button>
                  <Button
                    onClick={handleDownload}
                    className="flex-1"
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Download
                  </Button>
                </div>
              </CardContent>
            </Card>

            {/* Footer */}
            <div className="text-center mt-8 pt-8 border-t border-border">
              <p className="text-sm text-muted-foreground">
                <span className="font-semibold text-foreground">Columbia Business School</span>
                {' · '}Technology Strategy{' · '}Prof. Dan Wang
              </p>
            </div>
          </motion.div>
        </div>
      </main>
    </div>
  );
}
